options:
  charset: utf8
actAs: [Timestampable]

MemberGpsPosition:
  columns:
    id: { type: integer(4), primary: true, autoincrement: true }
    member_id: { type: integer(4), notnull: true }
    carrier: { type: integer(4), notnull: true }
  relations:
    Member:
      onDelete: cascade
